Модуляция
htmlacademy-javascript/1489759-kekstagram-23 pull request #4
Opened 2021-06-21 07:00 UTC by Dashulya1

2021-06-21 17:50 UTC, maxim-usikov requested changes
Пересмотри как загрузить модули на страницу: https://up.htmlacademy.ru/javascript/23/module/5/item/1

Тебе нужно загрузить все модули в `index.html`

Для того чтобы это сделать - нужно разместить пачку тегов script

```html
<script type="module" src="js/module_1_name.js"></script>
<script type="module" src="js/module_2_name.js"></script>
<script type="module" src="js/module_3_name.js"></script>
<script type="module" src="js/main.js"></script>
```

2021-06-21 17:50 UTC, maxim-usikov commented on js/idNum.js
> +}
Это надо обернуть в функцию и экспортировать функцию - а потом ее использовать.

2021-06-21 17:50 UTC, maxim-usikov commented on js/idReady.js
> +import {idNum} from './idNum.js';
```js
import { idNum } from './idNum.js';
```

Ничего не импортирует. Чтобы что-то импортировать, надо что-то экспортировать ;)

У тебя хороший пример в `./utils.js` - есть 2 функции, которые ты экспортируешь. А потом где хочешь импортируешь.


Пересмотри: https://up.htmlacademy.ru/javascript/23/module/5/item/4

2021-06-23 07:28 UTC, Dashulya1 commented
Линтер все равно ругается на короткие переменные, но все ошибки которые пишет находятся в удаленных файлах

2021-06-23 13:49 UTC, maxim-usikov approved these changes

2021-06-23 13:59 UTC, merged