Валидация комментария и хэштега
htmlacademy-javascript/1489759-kekstagram-23 pull request #7
Opened 2021-07-10 15:20 UTC by Dashulya1

Привет, сделала набросок. Не уверена, что полностью все, но что смогла)

2021-07-13 12:20 UTC, maxim-usikov requested changes
> 3. Проверьте разметку вашего проекта и добавьте недостающие атрибуты. Например, всем обязательным полям нужно добавить атрибут required. Затем проверьте, правильные ли типы стоят у нужных полей, если нет — проставьте правильные.

Не увидел атрибутов на полях в разметке.

- Пункт 1.1 не сделан: https://up.htmlacademy.ru/javascript/23/project/kekstagram#kekstagram-1-1

При клике на "загрузить" должна отображаться эта форма и в ней надо грузить изображения, заполнять поля и валидировать и тп.

- Пункт 1.2 не сделан: https://up.htmlacademy.ru/javascript/23/project/kekstagram#kekstagram-1-2

- Пункт 1.3 не сделан: https://up.htmlacademy.ru/javascript/23/project/kekstagram#kekstagram-1-3

- Пункт 2.3 не сделан: https://up.htmlacademy.ru/javascript/23/project/kekstagram#kekstagram-2-3

- Пункт 2.4 не сделан: https://up.htmlacademy.ru/javascript/23/project/kekstagram#kekstagram-2-4

- Пункт 3.2 не сделан: https://up.htmlacademy.ru/javascript/23/project/kekstagram#kekstagram-3-2


Ты сделала модули, но не загрузила и не используешь их. (простыми словами не импортировала их в main.js)

2021-07-13 12:20 UTC, maxim-usikov commented on js/form.js
> +  document.addEventListener('keydown', pushEscKeydown);
Ты добавляешь события при "закрытии" - почему не при "открытии"?

* При открытии нужно добавить события
* При закрытии удалить события

2021-07-13 12:20 UTC, maxim-usikov commented on js/validation.js
> +  const commentLenght = textOfComment.value.lenght;
Опечатка

```diff
- lenght
+ length
```

2021-07-13 18:01 UTC, Dashulya1 commented
Там в форме обязательное поле - загрузка фото, а про остальные в техзадании не указано, что они обязательные, поэтому я не добавляла required. У меня 2 ошибки в консоли, но я так и не разобралась почему) в остальном - подключила скрипты и подправила обработчики в открытии и закрытии формы

2021-07-14 07:00 UTC, maxim-usikov approved these changes

2021-07-14 07:00 UTC, merged